# Generated by Django 2.0.8 on 2018-08-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='extend_to_children',
            field=models.BooleanField(default=False, help_text='You can extent this template to children articles.They will be able to use this template without import.', verbose_name='extend to children'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_title',
            field=models.SlugField(unique=True, verbose_name='Template title'),
        ),
    ]
